apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      serviceAccountName: default
      containers:
        - name: mywebsite
          image: hoppusmac/demo-nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  type: ClusterIP
  selector:
    app: website
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website-external
spec:
  type: LoadBalancer
  selector:
    app: website
  ports:
    - name: http
      port: 80
      targetPort: 80
